analyzer:
  strong-mode:
    # mặc định là true, mình set rule này là false tức là ko cho phép ép kiểu ngầm định, phải tường minh
    implicit-casts: false

    # mặc định là true, mình set false, tức là ko cho phép sử dụng kiểu dynamic ngầm định
    # vì Dart nó cho phép bạn khai báo param mà ko cần kiểu, Dart sẽ tự hiểu param này có kiểu dynamic
    # Tuy nhiên, điều này làm cho việc đọc code hơi khó chịu nên mình đặt rule ngăn cấm
    implicit-dynamic: false
  errors:
    close_sinks: ignore

linter:
  rules:
    - annotate_overrides # phải sử dụng annotation overrides
    - avoid_empty_else # tránh sử dụng else mà bên trong không có code
    - avoid_function_literals_in_foreach_calls # kiểu cấm sử dụng lamdba trong forEach